# Generated by Django 3.0.6 on 2020-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
