# Generated by Django 2.2.6 on 2020-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleyapp', '0002_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='num',
            field=models.CharField(default='num', max_length=100),
        ),
    ]
