# Generated by Django 3.0.6 on 2020-05-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleyapp', '0003_bill_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='quant',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
